theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"
scrolloff = 999
rulers = [80]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.normal."space"]
Q = [":write-all", ":buffer-close-all", ":quit"]
q = [":write-all", ":buffer-close-all", ":quit"]
