# R
[[language]]
name = "r"
file-types = ["R", "Rmd"]
auto-format = true
language-servers = ["air", "r"]

[language-server.air]
command = "air"
args = ["language-server"]

# Python
[[language]]
name = "python"
file-types = ["py"]
language-servers = ["pyright"]
formatter = { command = "black", args = ["--fast", "-"] }
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

# C
[[language]]
name = "c"
file-types = ["c", "h"]
auto-format = true

[language.formatter]
command = "clang-format"
args = []

# LaTeX
[[language]]
name = "latex"
file-types = ["tex", "sty", "cls", "ltx"]
language-servers = ["texlab"]
formatter = { command = "latexindent", args = ["-l"], stdin = true }
auto-format = true

# Markdown
[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "- [ ]", ">"]

# Julia
[[language]]
name = "julia"
scope = "source.julia"
injection-regex = "julia"
file-types = ["jl"]
roots = ["Project.toml", "Manifest.toml", "JuliaProject.toml"]
comment-token = "#"
language-servers = ["julia"]
indent = { tab-width = 4, unit = "    " }

[language-server.julia]
command = "julia"
timeout = 60
args = ["-e", "using LanguageServer; runserver();"]
